name = "Frieserlabs blog"
license = "MIT"
licenselink = "https://github.com/frieserlabs/hugo-theme-novela/blob/master/LICENSE"
description = "A Hugo theme for Frieserlabs blog"
homepage = "blog.frieserlabs.dev"
tags = ["blog"]
features = ["dark mode", "grid view"]
min_version = "0.65.0"

[author]
    name = "frieser"
    homepage = "github.com/frieser"

# If porting an existing theme
[original]
    author = "Narative"
    homepage = "https://www.narative.co/"
    repo = "https://github.com/narative/gatsby-theme-novela"
